apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: replicator-deployment
spec:
  selector:
    matchLabels:
      app: replicator
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: replicator
    spec:
      containers:
      - name: replicator
        imagePullPolicy: Never
        image: replicator:1.0
        ports:
        - containerPort: 8080
        - containerPort: 2550