kind: Service
apiVersion: v1
metadata:
  name: replicator
spec:
  type: NodePort
  selector:
    app: replicator
  ports:
  - protocol: TCP
    name: mgmt
    port: 8081
    targetPort: mgmt
  - protocol: TCP
    name: api
    port: 8080
    targetPort: api